### ISSUE TITLE
NaN output

### ISSUE THREAD

**Issue by alexander-jamess** [LemaireJean-Baptiste/eventstudy#18]
![Screen Shot 2022-09-17 at 3 20 44 pm](https://user-images.githubusercontent.com/113752571/190841815-4cab8c21-d6c4-47b5-8a87-560a3c670354.png)

Hey!

Just wondering why I might be getting NaN output (see attached). For context, the package works for a smaller estimation window i.e., approx 30-40 days. But some reason it all goes to NaN after a certain threshold. I checked to see if there was enough data to estimate the model/ if there were any outliers etc. but doesn't seem to be the case.

Other securities work fine!

Cheers

**Comment by alexander-jamess** [comment]
Just through troubleshooting, it appears to be something to do with the buffer size. Not sure what buffer size is exactly though.

**Comment by LemaireJean-Baptiste** [comment]
Hello alexander-jamess,

To avoid any issue, you should download more data than necessary. By default, there is a 30-period buffer, which shifts the estimation window. (See the [documentation](https://lemairejean-baptiste.github.io/eventstudy/api/eventstudy.Single.market_model.html#eventstudy.Single.market_model).)

Buffer aims at preventing taking into account in the estimation window any potential leakage of information related to the event. What it does is simply shifting in the past the estimation window, to make it as unrelated to the analysed event as possible.

<img width="914" alt="Screenshot 2022-09-20 at 09 07 04" src="https://user-images.githubusercontent.com/7040049/191190234-39f982aa-89a7-4a72-a7dc-600ff3693969.png">

You can set it at zero if you don't need any buffer (ex : for unpredictable events or events with no chance of information leaks).

Your NaN error may come from that buffer. You can either remove it by specifying the `buffer_size` parameters at zero or you can also import more past data.

Best,
JB

**Comment by alexander-jamess** [comment]
Thank you very much. Super useful package by the way!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
