### ISSUE TITLE
.results

### ISSUE THREAD

**Issue by agarp149** [LemaireJean-Baptiste/eventstudy#7]
Hi, thank you for the package!

I am having some trouble showing the results when calling event.results(decimals=[3,5,3,5,2,2]).

The plot is working properly as is the get_CAR_dist().

The error I am receiving is:
if not indexes and not raw_lengths:
TypeError: object of type 'map' has no len()

Do you have any idea where I might have gone wrong?

Thanks again //agarp

**Comment by agarp149** [comment]
Hi did not see the closed issues, updating the packages worked. Cheers!

**Comment by LemaireJean-Baptiste** [comment]
Hi agarp,

Thank you for your message, Happy to see that last updates worked for you. Let me know if you have any comments/ideas on the tool.
